# Generated by Django 3.1.3 on 2020-12-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='ph_no',
            field=models.CharField(max_length=20),
        ),
    ]
