# Generated by Django 3.1.3 on 2020-12-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201210_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='e_mail',
            field=models.CharField(default='', max_length=50),
        ),
    ]
