# Generated by Django 3.1.3 on 2020-12-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registered_e_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_n', models.CharField(max_length=50)),
                ('middle_n', models.CharField(max_length=50)),
                ('last_n', models.CharField(max_length=50)),
                ('e_mail', models.CharField(default='', max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='NA', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='registered',
        ),
    ]
