# Generated by Django 3.1.3 on 2020-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201221_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='add_line1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='add_line2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='pin_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='primary_contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='secondary_contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_n',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_n',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='middle_n',
            field=models.CharField(default='', max_length=50),
        ),
    ]
