# Generated by Django 3.1.3 on 2020-12-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201221_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Expirience_in_Years',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='NPI_GMC_IMC_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='primary_speciality',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='profile_image',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='secondary_speciality',
            field=models.CharField(default='', max_length=30),
        ),
    ]
