# Generated by Django 3.1.3 on 2020-12-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201221_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_image',
            field=models.FileField(null=True, upload_to='mysite/images/', verbose_name=''),
        ),
    ]
