# Generated by Django 3.1.3 on 2020-12-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201221_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Comments',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Fellowship',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Honors_Awards_Recognition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Hospital_Privileges_to_practice',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Residency_SpecialistTraining_PG',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Resume_CV',
            field=models.FileField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Revalidation_ContinuingMedicalEducationYear',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='board_certification',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='medical_school',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='publication',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='states_to_practice',
            field=models.CharField(default='', max_length=50),
        ),
    ]
