# Generated by Django 3.1.3 on 2020-12-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201221_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
